
package Clases;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Mario
 */
public class Principal extends javax.swing.JFrame {

     int count;
    Baraja baraja = new Baraja();
    String rutaDorso;
    
    
    
    ActionListener al = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) { //El que se encarga de mostrar las cartas cada cierto tiempo
            if (count < baraja.getSize()) {
                mostrar();
            }    
        } 
    };
     Timer t = new Timer(3000, al); //Esto es el tiempo del timer
    public Principal() {
        initComponents();
        
          
        ButtonGroup bG = new ButtonGroup();
        bG.add(jRD1);
        bG.add(jRD2);
        bG.add(jRD3);
   
        
         this.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {

                switch (e.getKeyCode()) {
                    case KeyEvent.VK_SPACE:
                        jButPause.doClick();
                        break;

                    case KeyEvent.VK_ENTER:
                        jButPlay.doClick();
                        break;

                    default:
                        throw new AssertionError();
                }

            }

            @Override
            public void keyReleased(KeyEvent e) {
              
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabImagen = new javax.swing.JLabel();
        jButIniciar = new javax.swing.JButton();
        jButPartida = new javax.swing.JButton();
        jButPlay = new javax.swing.JButton();
        jButPause = new javax.swing.JButton();
        jLabPequeña = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFContador = new javax.swing.JTextField();
        jLabCartaSig = new javax.swing.JLabel();
        jLabCartaAnterior = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuColor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRD1 = new javax.swing.JRadioButtonMenuItem();
        jRD2 = new javax.swing.JRadioButtonMenuItem();
        jRD3 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loteria Mexicana");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setFocusable(false);

        jLabImagen.setBackground(new java.awt.Color(255, 255, 255));
        jLabImagen.setOpaque(true);

        jButIniciar.setText("Start");
        jButIniciar.setBorderPainted(false);
        jButIniciar.setFocusable(false);
        jButIniciar.setRequestFocusEnabled(false);
        jButIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButIniciarActionPerformed(evt);
            }
        });

        jButPartida.setText("New Game");
        jButPartida.setFocusable(false);
        jButPartida.setRequestFocusEnabled(false);
        jButPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPartidaActionPerformed(evt);
            }
        });

        jButPlay.setText("Play");
        jButPlay.setFocusPainted(false);
        jButPlay.setFocusable(false);
        jButPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPlayActionPerformed(evt);
            }
        });

        jButPause.setText("Pause");
        jButPause.setBorderPainted(false);
        jButPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButPause.setFocusPainted(false);
        jButPause.setFocusable(false);
        jButPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPauseActionPerformed(evt);
            }
        });

        jLabPequeña.setBackground(new java.awt.Color(255, 255, 255));
        jLabPequeña.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cards out:");

        jTFContador.setEditable(false);
        jTFContador.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFContador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabCartaSig.setBackground(new java.awt.Color(153, 153, 153));
        jLabCartaSig.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabCartaSig.setText(">");
        jLabCartaSig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabCartaSig.setOpaque(true);
        jLabCartaSig.setRequestFocusEnabled(false);
        jLabCartaSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabCartaSigMouseClicked(evt);
            }
        });

        jLabCartaAnterior.setBackground(new java.awt.Color(153, 153, 153));
        jLabCartaAnterior.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabCartaAnterior.setText("<");
        jLabCartaAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabCartaAnterior.setOpaque(true);
        jLabCartaAnterior.setRequestFocusEnabled(false);
        jLabCartaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabCartaAnteriorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFContador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jLabCartaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButPause, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addComponent(jLabPequeña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabCartaSig, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButIniciar)
                                .addGap(18, 18, 18)
                                .addComponent(jButPartida)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButPlay)
                                    .addComponent(jButPause))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabPequeña, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabCartaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(139, 139, 139))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabCartaSig, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFContador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenuColor.setText("Options");

        jMenuItem3.setText("Color");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuColor.add(jMenuItem3);

        jMenu1.setText("Deck");

        jRD1.setSelected(true);
        jRD1.setText("Deck 1");
        jRD1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRD1StateChanged(evt);
            }
        });
        jMenu1.add(jRD1);

        jRD2.setSelected(true);
        jRD2.setText("Deck 2");
        jRD2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRD2StateChanged(evt);
            }
        });
        jMenu1.add(jRD2);

        jRD3.setSelected(true);
        jRD3.setText("Deck 3");
        jRD3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRD3StateChanged(evt);
            }
        });
        jMenu1.add(jRD3);

        jMenuColor.add(jMenu1);

        jMenuItem1.setText("About Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuColor.add(jMenuItem1);

        jMenuBar1.add(jMenuColor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        iniciar();
        count=0; 
       
    }//GEN-LAST:event_formWindowOpened

    private void jButIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButIniciarActionPerformed
        // TODO add your handling code here:
        t.start();
    }//GEN-LAST:event_jButIniciarActionPerformed

    private void jButPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPartidaActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Seguro que quieres volver a empezar?");
        if (i == 0) {
            t.stop();
            baraja = new Baraja();
            iniciar();
            jTFContador.setText("");
        }
    }//GEN-LAST:event_jButPartidaActionPerformed

    private void jRD1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRD1StateChanged
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_jRD1StateChanged

    private void jRD2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRD2StateChanged
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_jRD2StateChanged

    private void jRD3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRD3StateChanged
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_jRD3StateChanged

    private void jButPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPauseActionPerformed
        // TODO add your handling code here:
        t.stop();
    }//GEN-LAST:event_jButPauseActionPerformed

    private void jButPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPlayActionPerformed
        // TODO add your handling code here:
        t.restart();
    }//GEN-LAST:event_jButPlayActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Color color;
        
        JColorChooser jcc = new JColorChooser();
        
        color = jcc.showDialog(null , "Selecciona un color" , Color.BLACK);
        
        this.jPanel1.setBackground(color);
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabCartaAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabCartaAnteriorMouseClicked
        // TODO add your handling code here:
           t.stop();
        
        this.jLabCartaSig.setEnabled(true);

        Carta c = baraja.mostrarCartasSacadasIzq();
        
        try{

        if (c == null) {
            this.jLabCartaAnterior.setEnabled(false);
        } else {
            ImageIcon pequeña = c.getImage();

            jLabPequeña.setIcon(new ImageIcon(pequeña.getImage().getScaledInstance(jLabPequeña.getWidth(),
                    jLabPequeña.getHeight(), Image.SCALE_SMOOTH)));
         }
            
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_jLabCartaAnteriorMouseClicked

    private void jLabCartaSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabCartaSigMouseClicked
        // TODO add your handling code here:
         this.jLabCartaAnterior.setEnabled(true);
        
        Carta c = baraja.mostrarCartasSacadasDer();

        try {
            if (c == null) {
                this.jLabCartaSig.setEnabled(false);
            } else {
                ImageIcon pequeña = c.getImage();

                jLabPequeña.setIcon(new ImageIcon(pequeña.getImage().getScaledInstance(jLabPequeña.getWidth(),
                        jLabPequeña.getHeight(), Image.SCALE_SMOOTH)));
            }

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jLabCartaSigMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Desarrollado por: \n"
                + "Mario Alberto Hernandez Macías",
                "AppLoteria v1.0",
                1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 public void iniciar(){
        
        if(jRD1.isSelected()){
            rutaDorso="img/dorso.jpg";
        } else if (jRD2.isSelected()){
            rutaDorso="img/dorso1.jpg";
        } else if (jRD3.isSelected()){
             rutaDorso="img/dorso2.jpg"; 
        }
        
        
         this.jLabImagen.setIcon( Imagenes.escalarImagen(new ImageIcon(rutaDorso), 
                        this.jLabImagen.getWidth(), 
                        this.jLabImagen.getHeight())
        );

         this.jLabPequeña.setIcon( Imagenes.escalarImagen(new ImageIcon(rutaDorso), 
                        this.jLabPequeña.getWidth(), 
                        this.jLabPequeña.getHeight())
        );

        count=0;
        
        jTFContador.setText(count + "");
    }
    
    public void mostrar(){
        try {  
            Carta c = baraja.sigCarta();
            Carta ca = baraja.antCarta();
            c.getAudio().play();
             

            this.jLabImagen.setIcon( Imagenes.escalarImagen(c.getImage(),this.jLabImagen.getWidth(),this.jLabImagen.getHeight()));
 
            this.jLabPequeña.setIcon( Imagenes.escalarImagen(ca.getImage(),this.jLabPequeña.getWidth(),this.jLabPequeña.getHeight()));

        } catch (Exception ex) {
            ex.toString();

        }
        count++;
        jTFContador.setText(count + "");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButIniciar;
    private javax.swing.JButton jButPartida;
    private javax.swing.JButton jButPause;
    private javax.swing.JButton jButPlay;
    private javax.swing.JLabel jLabCartaAnterior;
    private javax.swing.JLabel jLabCartaSig;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabPequeña;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuColor;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRD1;
    private javax.swing.JRadioButtonMenuItem jRD2;
    private javax.swing.JRadioButtonMenuItem jRD3;
    private javax.swing.JTextField jTFContador;
    // End of variables declaration//GEN-END:variables
}
